language: python
python:
  - 2.7
  - 3.5
  - 3.7-dev

branches:
  only:
    - master
    - /^\d+\.\d+.*$/

install:
  - pip install -r requirements.txt
  - pip install -r test_assets/requirements.txt
  - pip install coveralls

script:
  - make test
after_success:
  - coveralls

jobs:
  include:
    - stage: publish dev
      if: tag is blank and type != "pull_request"
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - make travis-dev
    - stage: publish release
      if: tag is present
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - make travis-tag TAG=$TRAVIS_TAG
        - echo $TRAVIS_TAG > VERSION
      deploy:
        provider: pypi
        user: fopina
        password: $PYPI_PASSWORD
        skip_cleanup: true
        on:
          tags: true
